### PR TITLE
XBoard Support Redux

### PR DESCRIPTION
**Pull request by ZirconiumX**
This took quite a bit of rebasing, but I got there in the end.

This code is quite messy because the XBoard and UCI APIs are different (I don't see why they should be), hopefully it can be cleaned up once merged.

### CODE REVIEW

**Comment by careless25** [comment]
Hmm, this will get messy. Can you make a class EngineWrapper? Then have 2 other classes UCI and Xboard inherit from it. Will make the code cleaner and easier to read

**Comment by ZirconiumX** [comment]
Sure, I can try that.

**Comment by ornicar** [comment]
After that's merged, we should consider renaming the repo.

**Comment by ZirconiumX** [comment]
How does this look?

**Comment by ornicar** [comment]
Looking good. Please make sure UCI engines still work.

**Comment by ZirconiumX** [comment]
Yeah, they work fine.

**Pull request merged**
